*** Variables ***
${SITE}                             https://hurb.com/br
${NAVEGADOR}                        Firefox
${BOTAO_PERMITIR_COOKIES}           xpath=//*[@id="CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll"]
${BOTAO_PACOTES}                    xpath=//*[@id="__next"]/div[1]/div[2]/div/div/div[1]/div/div/button[2]                              
${CAMPO_PESQUISA_CIDADE}            xpath=//*[@id="destination-input"]                        
${CIDADE}                           Buenos Aires
${BOTAO_PESQUISAR}                  xpath=//*[@id="__next"]/div[1]/div[2]/div/div/div[2]/button
${SELETOR_PACOTE_VIAGEM}            css=#__next > div > main > section > div.ResultsCardsContainer_ResultsCardContainer__CDDwR > a:nth-child(5)
${BOTAO_ESCOLHER_PACOTE}            xpath=//*[@id="__next"]/div/main/div[4]/aside/div/div/div[2]/button
${BOTAO_RADIO_ESCOLHER_PACOTE}      xpath=//*[@id="LGPKG-1138711-2776691"]
${BOTAO_PROXIMO_ESCOLHER_PACOTE}    xpath=//button[contains(.,'Próximo')]
${CIDADE_SAIDA}                     São Paulo
${TEMPO_VIAGEM}                     4 diárias
${BOTAO_SELECAO_DIARIA}             css=.h-cqz66k:nth-child(1) .h-1y6jkyf
${BOTAO_PROXIMO_ESCOLHER_DIARIA}    xpath=//button[contains(.,'Próximo')]
${BOTAO_IR_PAGAMENTO}               xpath=//button[contains(.,'Ir para pagamento')]
${PERIODO_VIAGEM_INICIO}            01 Mar 2023
${PERIODO_VIAGEM_FIM}               30 Nov 2023
${BOTAO_BOLETO_PARCELADO}           xpath=//*[@id="paymentMethods"]/ul/li[3]
${CAMPO_NOME_PAGADOR}               xpath=//*[@id="paymentMethods__bill"]/section/div[1]/div[1]/div/input
${NOME_PAGADOR}                     Kened Felix
${CAMPO_CPF_PAGADOR}                xpath=/html/body/div[3]/div/div[2]/div/div/form/div[5]/div[1]/div/div[2]/section/div[1]/div[2]/div/input
${CPF_PAGADOR}                      58636574252
${CAMPO_CELULAR_PAGADOR}            xpath=/html/body/div[3]/div/div[2]/div/div/form/div[5]/div[1]/div/div[2]/section/div[2]/div[1]/div/input
${CELULAR_PAGADOR}                  1699999999
${CHECKBOX}                         xpath=//*[@id="cancellation-policy"]
${TAG_CANCELAMENTO}                 Cancelamento Grátis!
${TEXT_CANCELAMENTO_GRATIS}         Só falta preencher os campos abaixo e garantir sua viagem!
${BOTAO_HOME}                       xpath=//*[@id="__next"]/div[1]/div[1]/header/div/div/div/div/div/div[1]

${BOTAO_PERMITIR_COOKIES2}           xpath=//*[@id="CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll"]
${BOTAO_PACOTES2}                    xpath=//*[@id="__next"]/div[1]/div[2]/div/div/div[1]/div/div/button[2]                              
${CAMPO_PESQUISA_CIDADE2}            xpath=//*[@id="destination-input"]                        
${CIDADE2}                           Buenos Aires
${BOTAO_PESQUISAR2}                  xpath=//*[@id="__next"]/div[1]/div[2]/div/div/div[2]/button
${SELETOR_PACOTE_VIAGEM2}            css=#__next > div > main > section > div.ResultsCardsContainer_ResultsCardContainer__CDDwR > a:nth-child(5)
${BOTAO_ESCOLHER_PACOTE2}            xpath=//*[@id="__next"]/div/main/div[4]/aside/div/div/div[2]/button
${BOTAO_RADIO_ESCOLHER_PACOTE2}      xpath=//*[@id="LGPKG-1138711-2776691"]
${BOTAO_PROXIMO_ESCOLHER_PACOTE2}    xpath=//button[contains(.,'Próximo')]
${CIDADE_SAIDA2}                     São Paulo
${TEMPO_VIAGEM2}                     4 diárias
${BOTAO_SELECAO_DIARIA2}             css=.h-cqz66k:nth-child(1) .h-1y6jkyf
${BOTAO_PROXIMO_ESCOLHER_DIARIA2}    xpath=//button[contains(.,'Próximo')]
${BOTAO_IR_PAGAMENTO2}               xpath=//button[contains(.,'Ir para pagamento')]
${PERIODO_VIAGEM_INICIO2}            01 Mar 2023
${PERIODO_VIAGEM_FIM2}               30 Nov 2023
${BOTAO_BOLETO_PARCELADO2}           xpath=//*[@id="paymentMethods"]/ul/li[3]
${CAMPO_NOME_PAGADOR2}               xpath=//*[@id="paymentMethods__bill"]/section/div[1]/div[1]/div/input
${NOME_PAGADOR2}                     Kened Felix
${CAMPO_CPF_PAGADOR2}                xpath=/html/body/div[3]/div/div[2]/div/div/form/div[5]/div[1]/div/div[2]/section/div[1]/div[2]/div/input
${CPF_PAGADOR2}                      58636574252
${CAMPO_CELULAR_PAGADOR2}            xpath=/html/body/div[3]/div/div[2]/div/div/form/div[5]/div[1]/div/div[2]/section/div[2]/div[1]/div/input
${CELULAR_PAGADOR2}                  1699999999
${CHECKBOX2}                         xpath=//*[@id="cancellation-policy"]
${TAG_CANCELAMENTO2}                 Cancelamento Grátis!
${TEXT_CANCELAMENTO_GRATIS2}         Só falta preencher os campos abaixo e garantir sua viagem!
${BOTAO_HOME2}                       xpath=//*[@id="__next"]/div[1]/div[1]/header/div/div/div/div/div/div[1]

${BOTAO_PERMITIR_COOKIES3}           xpath=//*[@id="CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll"]
${BOTAO_PACOTES3}                    xpath=//*[@id="__next"]/div[1]/div[2]/div/div/div[1]/div/div/button[2]                              
${CAMPO_PESQUISA_CIDADE3}            xpath=//*[@id="destination-input"]                        
${CIDADE3}                           Buenos Aires
${BOTAO_PESQUISAR3}                  xpath=//*[@id="__next"]/div[1]/div[2]/div/div/div[2]/button
${SELETOR_PACOTE_VIAGEM3}            css=#__next > div > main > section > div.ResultsCardsContainer_ResultsCardContainer__CDDwR > a:nth-child(5)
${BOTAO_ESCOLHER_PACOTE3}            xpath=//*[@id="__next"]/div/main/div[4]/aside/div/div/div[2]/button
${BOTAO_RADIO_ESCOLHER_PACOTE3}      xpath=//*[@id="LGPKG-1138711-2776691"]
${BOTAO_PROXIMO_ESCOLHER_PACOTE3}    xpath=//button[contains(.,'Próximo')]
${CIDADE_SAIDA3}                     São Paulo
${TEMPO_VIAGEM3}                     4 diárias
${BOTAO_SELECAO_DIARIA3}             css=.h-cqz66k:nth-child(1) .h-1y6jkyf
${BOTAO_PROXIMO_ESCOLHER_DIARIA3}    xpath=//button[contains(.,'Próximo')]
${BOTAO_IR_PAGAMENTO3}               xpath=//button[contains(.,'Ir para pagamento')]
${PERIODO_VIAGEM_INICIO3}            01 Mar 2023
${PERIODO_VIAGEM_FIM3}               30 Nov 2023
${BOTAO_BOLETO_PARCELADO3}           xpath=//*[@id="paymentMethods"]/ul/li[3]
${CAMPO_NOME_PAGADOR3}               xpath=//*[@id="paymentMethods__bill"]/section/div[1]/div[1]/div/input
${NOME_PAGADOR3}                     Kened Felix
${CAMPO_CPF_PAGADOR3}                xpath=/html/body/div[3]/div/div[2]/div/div/form/div[5]/div[1]/div/div[2]/section/div[1]/div[2]/div/input
${CPF_PAGADOR3}                      58636574252
${CAMPO_CELULAR_PAGADOR3}            xpath=/html/body/div[3]/div/div[2]/div/div/form/div[5]/div[1]/div/div[2]/section/div[2]/div[1]/div/input
${CELULAR_PAGADOR3}                  1699999999
${CHECKBOX3}                         xpath=//*[@id="cancellation-policy"]
${TAG_CANCELAMENTO3}                 Cancelamento Grátis!
${TEXT_CANCELAMENTO_GRATIS3}         Só falta preencher os campos abaixo e garantir sua viagem!
${BOTAO_HOME3}                       xpath=//*[@id="__next"]/div[1]/div[1]/header/div/div/div/div/div/div[1]

${BOTAO_PERMITIR_COOKIES4}           xpath=//*[@id="CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll"]
${BOTAO_PACOTES4}                    xpath=//*[@id="__next"]/div[1]/div[2]/div/div/div[1]/div/div/button[2]                              
${CAMPO_PESQUISA_CIDADE4}            xpath=//*[@id="destination-input"]                        
${CIDADE4}                           Buenos Aires
${BOTAO_PESQUISAR4}                  xpath=//*[@id="__next"]/div[1]/div[2]/div/div/div[2]/button
${SELETOR_PACOTE_VIAGEM4}            css=#__next > div > main > section > div.ResultsCardsContainer_ResultsCardContainer__CDDwR > a:nth-child(5)
${BOTAO_ESCOLHER_PACOTE4}            xpath=//*[@id="__next"]/div/main/div[4]/aside/div/div/div[2]/button
${BOTAO_RADIO_ESCOLHER_PACOTE4}      xpath=//*[@id="LGPKG-1138711-2776691"]
${BOTAO_PROXIMO_ESCOLHER_PACOTE4}    xpath=//button[contains(.,'Próximo')]
${CIDADE_SAIDA4}                     São Paulo
${TEMPO_VIAGEM4}                     4 diárias
${BOTAO_SELECAO_DIARIA4}             css=.h-cqz66k:nth-child(1) .h-1y6jkyf
${BOTAO_PROXIMO_ESCOLHER_DIARIA4}    xpath=//button[contains(.,'Próximo')]
${BOTAO_IR_PAGAMENTO4}               xpath=//button[contains(.,'Ir para pagamento')]
${PERIODO_VIAGEM_INICIO4}            01 Mar 2023
${PERIODO_VIAGEM_FIM4}               30 Nov 2023
${BOTAO_BOLETO_PARCELADO4}           xpath=//*[@id="paymentMethods"]/ul/li[3]
${CAMPO_NOME_PAGADOR4}               xpath=//*[@id="paymentMethods__bill"]/section/div[1]/div[1]/div/input
${NOME_PAGADOR4}                     Kened Felix
${CAMPO_CPF_PAGADOR4}                xpath=/html/body/div[3]/div/div[2]/div/div/form/div[5]/div[1]/div/div[2]/section/div[1]/div[2]/div/input
${CPF_PAGADOR4}                      58636574252
${CAMPO_CELULAR_PAGADOR4}            xpath=/html/body/div[3]/div/div[2]/div/div/form/div[5]/div[1]/div/div[2]/section/div[2]/div[1]/div/input
${CELULAR_PAGADOR4}                  1699999999
${CHECKBOX4}                         xpath=//*[@id="cancellation-policy"]
${TAG_CANCELAMENTO4}                 Cancelamento Grátis!
${TEXT_CANCELAMENTO_GRATIS4}         Só falta preencher os campos abaixo e garantir sua viagem!
${BOTAO_HOME4}                       xpath=//*[@id="__next"]/div[1]/div[1]/header/div/div/div/div/div/div[1]
                                        
*** Keywords ***
Abrir o site do Hurb
    Open Browser                    ${SITE}                 ${NAVEGADOR}
    Maximize Browser Window
    
Clicar em “Permitir todos os cookies”
    Sleep    5
    Wait and Click                  ${BOTAO_PERMITIR_COOKIES}
    Sleep    3

Selecionar a opção “Pacotes”
    Wait and Click                  ${BOTAO_PACOTES}
    Set Selenium Speed               0.5
    

Buscar por alguma cidade turística
    Input Text                       ${CAMPO_PESQUISA_CIDADE}   ${CIDADE}       
    Execute Javascript               window.scroll(0,350)
    Click Element                   ${BOTAO_PESQUISAR}
    Set Selenium Speed               0.5

Selecionar um pacote de viagem
    Sleep                            3
    Execute Javascript               window.scroll(0,350)
    Click Element                    ${SELETOR_PACOTE_VIAGEM}
    Switch Window                    NEW
    Execute Javascript               window.scroll(0,1300)
    Set Selenium Speed               0.5

Clicar em “Escolher pacote”
    Wait and Click                   ${BOTAO_ESCOLHER_PACOTE}
    Set Selenium Speed               2
    Page Should Contain              ${CIDADE_SAIDA}
    Wait Until Element is Visible    ${BOTAO_RADIO_ESCOLHER_PACOTE}
    Set Selenium Speed               2
    Click Element                    ${BOTAO_RADIO_ESCOLHER_PACOTE}
    Set Selenium Speed               2   
    Wait and Click                   ${BOTAO_PROXIMO_ESCOLHER_PACOTE}
    Set Selenium Speed               2
    Page Should Contain              ${TEMPO_VIAGEM} 
    Wait and Click                   ${BOTAO_SELECAO_DIARIA}
    Set Selenium Speed               2
    Wait and Click                   ${BOTAO_PROXIMO_ESCOLHER_DIARIA}
    Set Selenium Speed               2
    Wait and Click                   ${BOTAO_IR_PAGAMENTO}
    Set Selenium Speed               2

Selecionar a opção “Boleto parcelado”
    Wait Until Element is Visible     ${BOTAO_BOLETO_PARCELADO}
    Set Selenium Speed                2
    Click Element                     ${BOTAO_BOLETO_PARCELADO}
    Set Selenium Speed                2
   
Preencher os dados de pagamento
    Page Should Contain               ${TAG_CANCELAMENTO} 
    Page Should Contain               ${PERIODO_VIAGEM_INICIO}  
    Page Should Contain               ${PERIODO_VIAGEM_FIM} 
    Wait Until Element is Visible     ${CAMPO_NOME_PAGADOR}
    Execute Javascript                window.scroll(0,400)
    Input Text                        ${CAMPO_NOME_PAGADOR}       ${NOME_PAGADOR}
    Input Text                        ${CAMPO_CPF_PAGADOR}        ${CPF_PAGADOR}
    Input Text                        ${CAMPO_CELULAR_PAGADOR}    ${CELULAR_PAGADOR}
    Set Selenium Speed                2

Marcar o checkbox “Li e aceito as condições de termos de uso e política de privacidade”
    Select Checkbox                   ${CHECKBOX}
    Set Selenium Speed                2

 Validar a informação sobre cancelamento grátis
     Page Should Contain               ${TAG_CANCELAMENTO}
     Set Selenium Speed                2
     Sleep    2




Clicar em “Permitir todos os cookies”2
    Sleep    10
    Wait and Click                  ${BOTAO_PERMITIR_COOKIES2}
    Sleep    3

Selecionar a opção “Pacotes”2
    Wait and Click                  ${BOTAO_PACOTES2}
    Set Selenium Speed               0.5
    

Buscar por alguma cidade turística2
    Input Text                       ${CAMPO_PESQUISA_CIDADE2}   ${CIDADE2}       
    Execute Javascript               window.scroll(0,350)
    Click Element                   ${BOTAO_PESQUISAR2}
    Set Selenium Speed               0.5

Selecionar um pacote de viagem2
    Sleep                            3
    Execute Javascript               window.scroll(0,350)
    Click Element                    ${SELETOR_PACOTE_VIAGEM2}
    Switch Window                    NEW
    Execute Javascript               window.scroll(0,1300)
    Set Selenium Speed               0.5

Clicar em “Escolher pacote”2
    Wait and Click                   ${BOTAO_ESCOLHER_PACOTE2}
    Set Selenium Speed               2
    Page Should Contain              ${CIDADE_SAIDA2}
    Wait Until Element is Visible    ${BOTAO_RADIO_ESCOLHER_PACOTE2}
    Set Selenium Speed               2
    Click Element                    ${BOTAO_RADIO_ESCOLHER_PACOTE2}
    Set Selenium Speed               2   
    Wait and Click                   ${BOTAO_PROXIMO_ESCOLHER_PACOTE2}
    Set Selenium Speed               2
    Page Should Contain              ${TEMPO_VIAGEM2} 
    Wait and Click                   ${BOTAO_SELECAO_DIARIA2}
    Set Selenium Speed               2
    Wait and Click                   ${BOTAO_PROXIMO_ESCOLHER_DIARIA2}
    Set Selenium Speed               2
    Wait and Click                   ${BOTAO_IR_PAGAMENTO2}
    Set Selenium Speed               2

Selecionar a opção “Boleto parcelado”2
    Wait Until Element is Visible     ${BOTAO_BOLETO_PARCELADO2}
    Set Selenium Speed                2
    Click Element                     ${BOTAO_BOLETO_PARCELADO2}
    Set Selenium Speed                2
   
Preencher os dados de pagamento2
    Page Should Contain               ${TAG_CANCELAMENTO2} 
    Page Should Contain               ${PERIODO_VIAGEM_INICIO2}  
    Page Should Contain               ${PERIODO_VIAGEM_FIM2} 
    Wait Until Element is Visible     ${CAMPO_NOME_PAGADOR2}
    Execute Javascript                window.scroll(0,400)
    Input Text                        ${CAMPO_NOME_PAGADOR2}       ${NOME_PAGADOR2}
    Input Text                        ${CAMPO_CPF_PAGADOR2}        ${CPF_PAGADOR2}
    Input Text                        ${CAMPO_CELULAR_PAGADOR2}    ${CELULAR_PAGADOR2}
    Set Selenium Speed                2

Marcar o checkbox “Li e aceito as condições de termos de uso e política de privacidade”2
    Select Checkbox                   ${CHECKBOX2}
    Set Selenium Speed                2

 Validar a informação sobre cancelamento grátis2
     Page Should Contain               ${TAG_CANCELAMENTO2}
     Set Selenium Speed                2
     Sleep    2




Clicar em “Permitir todos os cookies”3
    Sleep    10
    Wait and Click                  ${BOTAO_PERMITIR_COOKIES3}
    Sleep    3

Selecionar a opção “Pacotes”3
    Wait and Click                  ${BOTAO_PACOTES3}
    Set Selenium Speed               0.5
    

Buscar por alguma cidade turística3
    Input Text                       ${CAMPO_PESQUISA_CIDADE3}   ${CIDADE3}       
    Execute Javascript               window.scroll(0,350)
    Click Element                   ${BOTAO_PESQUISAR3}
    Set Selenium Speed               0.5

Selecionar um pacote de viagem3
    Sleep                            3
    Execute Javascript               window.scroll(0,350)
    Click Element                    ${SELETOR_PACOTE_VIAGEM3}
    Switch Window                    NEW
    Execute Javascript               window.scroll(0,1300)
    Set Selenium Speed               0.5

Clicar em “Escolher pacote”3
    Wait and Click                   ${BOTAO_ESCOLHER_PACOTE3}
    Set Selenium Speed               2
    Page Should Contain              ${CIDADE_SAIDA3}
    Wait Until Element is Visible    ${BOTAO_RADIO_ESCOLHER_PACOTE3}
    Set Selenium Speed               2
    Click Element                    ${BOTAO_RADIO_ESCOLHER_PACOTE3}
    Set Selenium Speed               2   
    Wait and Click                   ${BOTAO_PROXIMO_ESCOLHER_PACOTE3}
    Set Selenium Speed               2
    Page Should Contain              ${TEMPO_VIAGEM3} 
    Wait and Click                   ${BOTAO_SELECAO_DIARIA3}
    Set Selenium Speed               2
    Wait and Click                   ${BOTAO_PROXIMO_ESCOLHER_DIARIA3}
    Set Selenium Speed               2
    Wait and Click                   ${BOTAO_IR_PAGAMENTO3}
    Set Selenium Speed               2

Selecionar a opção “Boleto parcelado”3
    Wait Until Element is Visible     ${BOTAO_BOLETO_PARCELADO3}
    Set Selenium Speed                2
    Click Element                     ${BOTAO_BOLETO_PARCELADO3}
    Set Selenium Speed                2
   
Preencher os dados de pagamento3
    Page Should Contain               ${TAG_CANCELAMENTO3} 
    Page Should Contain               ${PERIODO_VIAGEM_INICIO3}  
    Page Should Contain               ${PERIODO_VIAGEM_FIM3} 
    Wait Until Element is Visible     ${CAMPO_NOME_PAGADOR3}
    Execute Javascript                window.scroll(0,400)
    Input Text                        ${CAMPO_NOME_PAGADOR3}       ${NOME_PAGADOR3}
    Input Text                        ${CAMPO_CPF_PAGADOR3}        ${CPF_PAGADOR3}
    Input Text                        ${CAMPO_CELULAR_PAGADOR3}    ${CELULAR_PAGADOR3}
    Set Selenium Speed                2

Marcar o checkbox “Li e aceito as condições de termos de uso e política de privacidade”3
    Select Checkbox                   ${CHECKBOX3}
    Set Selenium Speed                2

 Validar a informação sobre cancelamento grátis3
     Page Should Contain               ${TAG_CANCELAMENTO3}
     Set Selenium Speed                2
     Sleep    2



Clicar em “Permitir todos os cookies”4
    Sleep    10
    Wait and Click                  ${BOTAO_PERMITIR_COOKIES4}
    Sleep    3

Selecionar a opção “Pacotes”4
    Wait and Click                  ${BOTAO_PACOTES4}
    Set Selenium Speed               0.5
    

Buscar por alguma cidade turística4
    Input Text                       ${CAMPO_PESQUISA_CIDADE4}   ${CIDADE4}       
    Execute Javascript               window.scroll(0,350)
    Click Element                   ${BOTAO_PESQUISAR4}
    Set Selenium Speed               0.5

Selecionar um pacote de viagem4
    Sleep                            3
    Execute Javascript               window.scroll(0,350)
    Click Element                    ${SELETOR_PACOTE_VIAGEM4}
    Switch Window                    NEW
    Execute Javascript               window.scroll(0,1300)
    Set Selenium Speed               0.5

Clicar em “Escolher pacote”4
    Wait and Click                   ${BOTAO_ESCOLHER_PACOTE4}
    Set Selenium Speed               2
    Page Should Contain              ${CIDADE_SAIDA4}
    Wait Until Element is Visible    ${BOTAO_RADIO_ESCOLHER_PACOTE4}
    Set Selenium Speed               2
    Click Element                    ${BOTAO_RADIO_ESCOLHER_PACOTE4}
    Set Selenium Speed               2   
    Wait and Click                   ${BOTAO_PROXIMO_ESCOLHER_PACOTE4}
    Set Selenium Speed               2
    Page Should Contain              ${TEMPO_VIAGEM4} 
    Wait and Click                   ${BOTAO_SELECAO_DIARIA4}
    Set Selenium Speed               2
    Wait and Click                   ${BOTAO_PROXIMO_ESCOLHER_DIARIA4}
    Set Selenium Speed               2
    Wait and Click                   ${BOTAO_IR_PAGAMENTO4}
    Set Selenium Speed               2

Selecionar a opção “Boleto parcelado”4
    Wait Until Element is Visible     ${BOTAO_BOLETO_PARCELADO4}
    Set Selenium Speed                2
    Click Element                     ${BOTAO_BOLETO_PARCELADO4}
    Set Selenium Speed                2
   
Preencher os dados de pagamento4
    Page Should Contain               ${TAG_CANCELAMENTO4} 
    Page Should Contain               ${PERIODO_VIAGEM_INICIO4}  
    Page Should Contain               ${PERIODO_VIAGEM_FIM4} 
    Wait Until Element is Visible     ${CAMPO_NOME_PAGADOR4}
    Execute Javascript                window.scroll(0,400)
    Input Text                        ${CAMPO_NOME_PAGADOR4}       ${NOME_PAGADOR4}
    Input Text                        ${CAMPO_CPF_PAGADOR4}        ${CPF_PAGADOR4}
    Input Text                        ${CAMPO_CELULAR_PAGADOR4}    ${CELULAR_PAGADOR4}
    Set Selenium Speed                2

Marcar o checkbox “Li e aceito as condições de termos de uso e política de privacidade”4
    Select Checkbox                   ${CHECKBOX4}
    Set Selenium Speed                2

 Validar a informação sobre cancelamento grátis4
     Page Should Contain               ${TAG_CANCELAMENTO4}
     Set Selenium Speed                2
     Sleep    2


Wait and Click
  [Arguments]                       ${ELEMENTO}
  Wait Until Element is Visible     ${ELEMENTO}
  Click Element                     ${ELEMENTO}